server:
  port: 0

app:
  client:
    url: http://SuperMart.com



spring:
  application:
    name: auth-management
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: 'postgres'
    password: '12345678'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

encryption:
  salt:
    rounds: 10